version: '3'
services:
  postgresDB:
    container_name: giftToGoPostgresDB
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: GiftToGo_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

#  myspringboot:
#    build: .
#    restart: unless-stopped
#    depends_on:
#      - postgresDB
#    networks:
#      - postgres
#    ports:
#      - 8080:8080

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
